// Variables for buttons
const field1 = document.querySelector("#field1"); // This is for our "Noun" button.........
const field2 = document.querySelector("#field2"); // This is for our "Action" button........
const field3 = document.querySelector("#field3"); // This is for our "Sound Effect" button.....
const field4 = document.querySelector("#field4"); // This is another "Noun" button........
const field5 = document.querySelector("#field5"); // This is for our "Place" button.........
const submit = document.querySelector("#submit"); // This is the button to see our story........
const randomstory = document.querySelector("#randomstory"); // This is the button to generate a random story.....

let clicked = false;

// Event listeners for buttons.....
field1.addEventListener("click", list1); // When we click on a "Noun" button, it updates our story with a new noun......
field2.addEventListener("click", list2); // When we click on an "Action" button, it updates our story with a new action.......
field3.addEventListener("click", list3); // When we click on a "Sound Effect" button, it updates our story with a new sound effect....
field4.addEventListener("click", list4); // When we click on another "Noun" button, it updates our story with another noun.....
field5.addEventListener("click", list5); // When we click on a "Place" button, it updates our story with a new place.......
randomstory.addEventListener("click", list6); // When we click on "Random Story", it generates a random story for us........

// story array.........
let storyarray = ["The Turkey", "Sits on", "A funny", "girafe", "On the moon"]; // Our initial story parts

// Arrays for story parts...........
const arrays = [
    ["The Turkey", "Mom", "Dad", "The Dog", "My Teacher", "THE Elephant", "The Cat"], // Array of nouns......
    ["Sits on", "Eats", "Kissed", "Danced With", "Doesn't like", "Saw"], // Array of actions.......
    ["A funny", "A scary", "A goofy", "A slimmy", "A barking", "A fat"], // Array of sound effects.......
    ["girafe", "monkey", "fish", "cow", "frog", "bug", "snake"], // Array of nouns......
    ["On the moon", "On the chair", "in my spagetti", "in my shoe", "in my soup", "on the grass"] // Array of places.....
];

// Function to update story parts when a specific button is clicked.........
function updateStory(index) {
    if (clicked) { // If we've already clicked on a button.........
        const storyPart = arrays[index].find((part) => part === storyarray[index]); 
        const currentIndex = arrays[index].indexOf(storyPart); 
        if (currentIndex < arrays[index].length - 1) { // If we're not at the end of the array........
            storyarray[index] = arrays[index][currentIndex + 1]; 
        }
    }
}

// Event listeners for each button to update the story parts......
function list1() { updateStory(0); } 
function list2() { updateStory(1); }
function list3() { updateStory(2); } 
function list4() { updateStory(3); }
function list5() { updateStory(4); } 

// Function to generate a random story........
function list6() {
    clicked = true;
    storyarray = arrays.map((array) => array[Math.floor(Math.random() * array.length)]); // Randomly select story parts
}

// Event listener for the submit button to display the generated story..........
submit.addEventListener('click', function() {
    const output = document.querySelector("#output"); 
    output.textContent = storyarray.join(' ');
});
